<?php

namespace backend\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "department".
 *
 * @property integer $id
 * @property string $name
 * @property integer $pid
 * @property string $createTime
 * @property integer $status
 */
class Department extends \yii\db\ActiveRecord
{

    /**
     * 启用
     */
    const STATUS_ENABLED = 1;
    /**
     * 禁用
     */
    const STATUS_DISABLED = 0;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'department';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['pid', 'status'], 'integer'],
            [['createTime'], 'safe'],
            [['name'], 'string', 'max' => 15],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => '主键',
            'name' => '部门名称',
            'pid' => '上级部门',
            'createTime' => '创建时间',
            'status' => '状态',
        ];
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        if(empty($this->pid)) {
            $this->pid = 0;
        }
        $this->createTime = date('Y-m-d H:i:s');
        $this->status = self::STATUS_ENABLED;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     */
    public static function map()
    {
        $map = self::find()->select(['id', 'name'])->where(['status' => self::STATUS_ENABLED])->asArray()->all();
        return ArrayHelper::map($map, 'id', 'name');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDName()
    {
        return $this->hasOne(self::className(), ['id' => 'pid']);
    }
}